import React,{useState}from"react";
import{ArrowLeft,RotateCcw}from"lucide-react";
import{Switch}from"@/components/ui/switch";
export type NotificationPrefs={messages:boolean;groups:boolean;reactions:boolean;sound:boolean;vibrate:boolean;preview:boolean;badge:boolean};
const DEFAULTS:NotificationPrefs={messages:true,groups:true,reactions:true,sound:true,vibrate:true,preview:true,badge:true};
export const notificationPrefsKey=(uid:string)=>`pf-community-notifications:${uid}`;
export const readNotificationPrefs=(uid:string):NotificationPrefs=>{try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(notificationPrefsKey(uid))||"")}}catch{return DEFAULTS}};
export default function CommunityNotificationSettings({uid,onClose}:{uid:string;onClose:()=>void}){
 const[p,setP]=useState(()=>readNotificationPrefs(uid));
 const setPref=(k:keyof NotificationPrefs,v:boolean)=>{const n={...p,[k]:v};setP(n);localStorage.setItem(notificationPrefsKey(uid),JSON.stringify(n))};
 const row=(label:string,k:keyof NotificationPrefs)=><div className="h-14 px-4 flex items-center border-b border-white/5 last:border-0"><span className="flex-1">{label}</span><Switch checked={p[k]} onCheckedChange={v=>setPref(k,v)}/></div>;
 return <div className="fixed inset-0 z-[150] bg-[#080808] text-white overflow-y-auto" style={{paddingTop:"env(safe-area-inset-top)",paddingBottom:"env(safe-area-inset-bottom)"}}><header className="sticky top-0 h-16 bg-black/95 border-b border-white/10 px-3 flex items-center gap-3"><button onClick={onClose} className="w-10 h-10 grid place-items-center"><ArrowLeft/></button><b>Notifications</b></header><div className="p-4 space-y-5"><section><div className="px-2 pb-2 text-xs uppercase tracking-widest text-zinc-500 font-bold">Community</div><div className="rounded-2xl overflow-hidden bg-zinc-950 border border-white/10">{row("Message notifications","messages")}{row("Group notifications","groups")}{row("Reaction notifications","reactions")}</div></section><section><div className="px-2 pb-2 text-xs uppercase tracking-widest text-zinc-500 font-bold">Alerts</div><div className="rounded-2xl overflow-hidden bg-zinc-950 border border-white/10">{row("Sound","sound")}{row("Vibrate","vibrate")}{row("Show preview","preview")}{row("App icon / unread badge","badge")}</div></section><button onClick={()=>{setP(DEFAULTS);localStorage.setItem(notificationPrefsKey(uid),JSON.stringify(DEFAULTS))}} className="w-full h-13 py-3 rounded-2xl bg-zinc-950 border border-white/10 flex justify-center items-center gap-2 text-orange-400"><RotateCcw className="w-5 h-5"/>Reset notification settings</button></div></div>;
}
