import React,{useEffect,useMemo,useRef,useState}from"react";
import{ArrowLeft,Bell,BellOff,Camera,ChevronRight,Heart,LogOut,Mic,MoreHorizontal,Paperclip,Plus,Search,Send,Settings,Users,Video,Phone,X}from"lucide-react";
import{supabase}from"@/integrations/supabase/client";
import CreateGroupModal,{type CreatedGroup}from"@/components/community/CreateGroupModal";
import entryLogo from"@/assets/prayer-fire-entry-logo.png";

type Group=CreatedGroup&{role?:string;muted?:boolean;favorite?:boolean;archived?:boolean;memberCount?:number;description?:string};
type Msg={id:string;sender_id:string;body?:string|null;media_url?:string|null;media_type?:string|null;created_at:string;mine?:boolean;url?:string};
const db:any=supabase;
const lang=()=>{const x=(localStorage.getItem("pf_lang")||"en").slice(0,2);return x==="es"||x==="pt"?x:"en"};
const tx={en:{title:"Community",search:"Search chats",empty:"No chats yet",sub:"Your conversations will appear here.",new:"New group",members:"members",info:"Group info",mute:"Mute notifications",unmute:"Unmute notifications",fav:"Favorite group",exit:"Exit group",edit:"Edit group",desc:"Description",save:"Save",type:"Message Prayer & Fire"},es:{title:"Comunidad",search:"Buscar chats",empty:"Todavía no hay chats",sub:"Tus conversaciones aparecerán aquí.",new:"Nuevo grupo",members:"miembros",info:"Información del grupo",mute:"Silenciar notificaciones",unmute:"Activar notificaciones",fav:"Grupo favorito",exit:"Salir del grupo",edit:"Editar grupo",desc:"Descripción",save:"Guardar",type:"Mensaje Prayer & Fire"},pt:{title:"Comunidade",search:"Buscar chats",empty:"Ainda não há conversas",sub:"Suas conversas aparecerão aqui.",new:"Novo grupo",members:"membros",info:"Informações do grupo",mute:"Silenciar notificações",unmute:"Ativar notificações",fav:"Grupo favorito",exit:"Sair do grupo",edit:"Editar grupo",desc:"Descrição",save:"Salvar",type:"Mensagem Prayer & Fire"}} as const;

export default function CommunityEnhanced(){
 const L=lang(),t=tx[L]; const[me,setMe]=useState<any>(null),[groups,setGroups]=useState<Group[]>([]),[selected,setSelected]=useState<Group|null>(null),[msgs,setMsgs]=useState<Msg[]>([]),[q,setQ]=useState(""),[create,setCreate]=useState(false),[info,setInfo]=useState(false),[draft,setDraft]=useState(""),[rec,setRec]=useState(false),[edit,setEdit]=useState(false),[name,setName]=useState(""),[desc,setDesc]=useState("");
 const file=useRef<HTMLInputElement>(null),photo=useRef<HTMLInputElement>(null),mr=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<number|null>(null),end=useRef<HTMLDivElement>(null);
 const signed=async(path?:string|null)=>{if(!path)return undefined;const{data}=await supabase.storage.from("community-media").createSignedUrl(path,3600);return data?.signedUrl};
 const loadGroups=async(uid:string)=>{const{data:m}=await db.from("community_group_members").select("group_id,role,muted,archived,favorite").eq("user_id",uid);const ids=(m||[]).map((x:any)=>x.group_id);if(!ids.length)return setGroups([]);const{data:g}=await db.from("community_groups").select("id,name,description,avatar_url,updated_at").in("id",ids).order("updated_at",{ascending:false});const mm=new Map((m||[]).map((x:any)=>[x.group_id,x]));setGroups(await Promise.all((g||[]).map(async(x:any)=>{const z:any=mm.get(x.id)||{};const{count}=await db.from("community_group_members").select("*",{count:"exact",head:true}).eq("group_id",x.id);return{id:x.id,name:x.name,subtitle:x.description||`${count||0} ${t.members}`,description:x.description||"",unread:0,lastTime:new Date(x.updated_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}),avatar:x.avatar_url?await signed(x.avatar_url):undefined,role:z.role,muted:z.muted,archived:z.archived,favorite:z.favorite,memberCount:count||0}})))};
 const loadMsgs=async(id:string)=>{const{data}=await db.from("community_messages").select("id,sender_id,body,media_url,media_type,created_at,deleted_at").eq("group_id",id).is("deleted_at",null).order("created_at");setMsgs(await Promise.all((data||[]).map(async(x:any)=>({...x,mine:x.sender_id===me?.id,url:x.media_url?await signed(x.media_url):undefined}))));setTimeout(()=>end.current?.scrollIntoView(),20)};
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:p}=await db.from("profiles").select("username,avatar_url").eq("id",user.id).maybeSingle();const x={id:user.id,name:p?.username||user.email?.split("@")[0]||"Prayer & Fire Member",avatar:p?.avatar_url};setMe(x);loadGroups(user.id)})()},[]);
 useEffect(()=>{if(!selected)return;loadMsgs(selected.id);const c=supabase.channel(`chat:${selected.id}`).on("postgres_changes",{event:"*",schema:"public",table:"community_messages",filter:`group_id=eq.${selected.id}`},()=>loadMsgs(selected.id)).subscribe();return()=>{supabase.removeChannel(c)}},[selected?.id,me?.id]);
 useEffect(()=>{if(!me)return;const c=supabase.channel(`list:${me.id}`).on("postgres_changes",{event:"*",schema:"public",table:"community_group_members",filter:`user_id=eq.${me.id}`},()=>loadGroups(me.id)).on("postgres_changes",{event:"*",schema:"public",table:"community_groups"},()=>loadGroups(me.id)).subscribe();return()=>{supabase.removeChannel(c)}},[me?.id]);
 const visible=useMemo(()=>groups.filter(g=>!g.archived&&(g.name+g.subtitle).toLowerCase().includes(q.toLowerCase())),[groups,q]);
 const createGroup=async(g:CreatedGroup)=>{if(!me)return;let path:string|undefined;if(g.avatar?.startsWith("blob:")){const b=await fetch(g.avatar).then(r=>r.blob());path=`${me.id}/groups/${crypto.randomUUID()}.jpg`;await supabase.storage.from("community-media").upload(path,b,{contentType:b.type||"image/jpeg"})}const{data:x,error}=await db.from("community_groups").insert({name:g.name,description:g.subtitle,avatar_url:path||null,created_by:me.id}).select().single();if(error)return;await db.from("community_group_members").insert([{group_id:x.id,user_id:me.id,role:"owner"},...(g.memberIds||[]).map(id=>({group_id:x.id,user_id:id,role:"member"}))]);await loadGroups(me.id)};
 const send=async()=>{if(!draft.trim()||!selected||!me)return;await db.from("community_messages").insert({group_id:selected.id,sender_id:me.id,body:draft.trim().slice(0,10000)});setDraft("")};
 const upload=async(f?:File)=>{if(!f||!selected||!me||f.size>25*1024*1024)return;const kind=f.type.startsWith("image/")?"image":f.type.startsWith("video/")?"video":f.type.startsWith("audio/")?"audio":"document";const path=`${me.id}/${selected.id}/${Date.now()}-${f.name}`;const{error}=await supabase.storage.from("community-media").upload(path,f,{contentType:f.type});if(!error)await db.from("community_messages").insert({group_id:selected.id,sender_id:me.id,media_url:path,media_type:kind})};
 const record=async()=>{if(rec){mr.current?.stop();return}const s=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(s);chunks.current=[];r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=async()=>{s.getTracks().forEach(x=>x.stop());setRec(false);if(timer.current)clearTimeout(timer.current);await upload(new File([new Blob(chunks.current,{type:r.mimeType||"audio/webm"})],`voice-${Date.now()}.webm`,{type:r.mimeType||"audio/webm"}))};mr.current=r;r.start();setRec(true);timer.current=window.setTimeout(()=>r.state!=="inactive"&&r.stop(),20*60*1000)};
 const memberUpdate=async(ch:any)=>{if(!selected||!me)return;await db.from("community_group_members").update(ch).eq("group_id",selected.id).eq("user_id",me.id);setSelected(s=>s?{...s,...ch}:s);setGroups(v=>v.map(g=>g.id===selected.id?{...g,...ch}:g))};
 const saveGroup=async()=>{if(!selected||!(selected.role==="owner"||selected.role==="admin"))return;await db.from("community_groups").update({name:name.trim()||selected.name,description:desc.trim(),updated_at:new Date().toISOString()}).eq("id",selected.id);setSelected(s=>s?{...s,name:name.trim()||s.name,description:desc.trim(),subtitle:desc.trim()||s.subtitle}:s);setEdit(false)};
 const changePhoto=async(f?:File)=>{if(!f||!selected||!me||!(selected.role==="owner"||selected.role==="admin"))return;const path=`${me.id}/groups/${selected.id}-${Date.now()}.jpg`;await supabase.storage.from("community-media").upload(path,f,{contentType:f.type,upsert:true});await db.from("community_groups").update({avatar_url:path}).eq("id",selected.id);setSelected(s=>s?{...s,avatar:await signed(path)}:s)};
 const leave=async()=>{if(!selected||!me)return;await db.from("community_group_members").delete().eq("group_id",selected.id).eq("user_id",me.id);setSelected(null);setInfo(false);loadGroups(me.id)};
 if(selected&&info)return <div className="fixed inset-0 bg-[#080808] text-white overflow-y-auto" style={{paddingTop:"env(safe-area-inset-top)",paddingBottom:"env(safe-area-inset-bottom)"}}><header className="sticky top-0 h-16 bg-black/95 border-b border-white/10 px-3 flex items-center gap-3"><button onClick={()=>setInfo(false)}><ArrowLeft/></button><b className="flex-1">{t.info}</b>{(selected.role==="owner"||selected.role==="admin")&&<button onClick={()=>{setName(selected.name);setDesc(selected.description||"");setEdit(true)}}><Settings/></button>}</header><div className="p-6 text-center border-b border-white/10"><button onClick={()=>photo.current?.click()} className="relative w-28 h-28 rounded-full overflow-hidden bg-zinc-900"><img src={selected.avatar||entryLogo} className="w-full h-full object-cover"/><span className="absolute bottom-0 inset-x-0 bg-black/70 py-2 flex justify-center"><Camera className="w-5 h-5"/></span></button><input ref={photo} type="file" accept="image/*" className="hidden" onChange={e=>changePhoto(e.target.files?.[0])}/><h2 className="text-2xl font-black mt-4">{selected.name}</h2><p className="text-zinc-400 text-sm">{selected.memberCount||0} {t.members}</p><p className="mt-3 text-zinc-300">{selected.description}</p></div><div className="m-4 rounded-2xl overflow-hidden border border-white/10 bg-zinc-950"><button onClick={()=>memberUpdate({muted:!selected.muted})} className="w-full h-14 px-4 flex items-center gap-3 border-b border-white/5">{selected.muted?<Bell/>:<BellOff/>}<span className="flex-1 text-left">{selected.muted?t.unmute:t.mute}</span><ChevronRight/></button><button onClick={()=>memberUpdate({favorite:!selected.favorite})} className="w-full h-14 px-4 flex items-center gap-3"><Heart className={selected.favorite?"fill-current text-orange-500":""}/><span className="flex-1 text-left">{t.fav}</span></button></div><div className="m-4 rounded-2xl border border-white/10 bg-zinc-950"><button onClick={leave} className="w-full h-14 px-4 flex items-center gap-3 text-red-400"><LogOut/><span>{t.exit}</span></button></div>{edit&&<div className="fixed inset-0 bg-black/70 flex items-end"><div className="w-full rounded-t-3xl bg-zinc-950 p-5"><div className="flex justify-between"><b>{t.edit}</b><button onClick={()=>setEdit(false)}><X/></button></div><input value={name} onChange={e=>setName(e.target.value)} className="mt-5 w-full h-12 bg-zinc-900 rounded-xl px-3"/><textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder={t.desc} className="mt-3 w-full bg-zinc-900 rounded-xl p-3" rows={4}/><button onClick={saveGroup} className="mt-4 w-full h-12 rounded-xl bg-orange-500 text-black font-black">{t.save}</button></div></div>}</div>;
 if(selected)return <div className="fixed inset-0 bg-[#080808] text-white flex flex-col" style={{paddingTop:"env(safe-area-inset-top)",paddingBottom:"env(safe-area-inset-bottom)"}}><header className="h-16 px-2 bg-black/95 border-b border-white/10 flex items-center gap-2"><button onClick={()=>setSelected(null)} className="w-10"><ArrowLeft/></button><button onClick={()=>setInfo(true)} className="flex-1 min-w-0 flex items-center gap-2 text-left"><img src={selected.avatar||entryLogo} className="w-11 h-11 rounded-full object-cover"/><div className="min-w-0"><b className="block truncate">{selected.name}</b><span className="text-xs text-zinc-400">{selected.memberCount||0} {t.members}</span></div></button><Video/><Phone/><button onClick={()=>setInfo(true)}><MoreHorizontal/></button></header><main className="flex-1 overflow-y-auto p-3 space-y-2">{msgs.map(m=><div key={m.id} className={`flex ${m.mine?"justify-end":"justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-3 py-2 ${m.mine?"bg-orange-500 text-black":"bg-zinc-900"}`}>{m.body&&<p className="whitespace-pre-wrap">{m.body}</p>}{m.media_type==="image"&&m.url&&<img src={m.url} className="rounded-xl max-h-80"/>}{m.media_type==="video"&&m.url&&<video src={m.url} controls className="rounded-xl max-h-80"/>}{m.media_type==="audio"&&m.url&&<audio src={m.url} controls/>}<div className="text-[10px] opacity-60 text-right mt-1">{new Date(m.created_at).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}{m.mine&&<CheckCheck className="inline w-3 h-3 ml-1"/>}</div></div></div>)}<div ref={end}/></main><div className="p-2 border-t border-white/10 flex gap-2"><button onClick={()=>file.current?.click()} className="w-11 rounded-full bg-zinc-900 grid place-items-center"><Paperclip/></button><input ref={file} type="file" className="hidden" accept="image/*,video/*,audio/*,.pdf,.doc,.docx,.txt" onChange={e=>{upload(e.target.files?.[0]);e.target.value=""}}/><div className="flex-1 bg-zinc-900 rounded-full px-4 flex"><input maxLength={10000} value={draft} onChange={e=>setDraft(e.target.value)} placeholder={t.type} className="flex-1 bg-transparent outline-none"/><button onClick={()=>file.current?.click()}><Camera/></button></div>{draft.trim()?<button onClick={send} className="w-11 h-11 rounded-full bg-orange-500 text-black grid place-items-center"><Send/></button>:<button onClick={record} className={`w-11 h-11 rounded-full grid place-items-center ${rec?"bg-red-500":"bg-orange-500 text-black"}`}><Mic/></button>}</div></div>;
 return <div className="fixed inset-0 bg-black text-white" style={{paddingTop:"env(safe-area-inset-top)",paddingBottom:"env(safe-area-inset-bottom)"}}><div className="max-w-xl mx-auto h-full flex flex-col"><header className="px-4 py-2 min-h-16 border-b border-white/10 flex items-center gap-3"><img src={me?.avatar||entryLogo} className="w-11 h-11 rounded-full object-cover"/><div className="flex-1 min-w-0"><span className="text-[9px] tracking-[.2em] text-orange-400 font-bold">PRAYER & FIRE</span><h1 className="font-black text-xl truncate">{t.title}</h1></div><button onClick={()=>setCreate(true)} className="w-10 h-10 rounded-full bg-orange-500 text-black grid place-items-center" aria-label={t.new}><Plus/></button></header><div className="p-4"><div className="h-12 rounded-2xl bg-zinc-900 px-4 flex items-center gap-2"><Search className="text-zinc-500"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} className="bg-transparent outline-none flex-1"/></div></div><main className="flex-1 overflow-y-auto px-3">{visible.length?visible.map(g=><button key={g.id} onClick={()=>setSelected(g)} className="w-full flex gap-3 p-3 border-b border-white/10 text-left"><img src={g.avatar||entryLogo} className="w-14 h-14 rounded-full object-cover"/><div className="min-w-0 flex-1"><b className="block truncate">{g.name}</b><span className="text-sm text-zinc-400 truncate block">{g.subtitle}</span></div></button>):<div className="py-24 text-center"><Users className="mx-auto w-12 h-12 text-orange-500"/><h2 className="font-black text-xl mt-4">{t.empty}</h2><p className="text-zinc-500 mt-2">{t.sub}</p></div>}</main><CreateGroupModal open={create} onClose={()=>setCreate(false)} onCreate={createGroup} language={L}/></div></div>;
}
