export const LANGUAGES = [
  { code: "af", name: "Afrikaans" },
  { code: "sq", name: "Albanian - Shqip" },
  { code: "am", name: "Amharic - አማርኛ" },
  { code: "ar", name: "Arabic - العربية" },
  { code: "hy", name: "Armenian - Հայերեն" },
  { code: "az", name: "Azerbaijani - Azərbaycan" },
  { code: "eu", name: "Basque - Euskara" },
  { code: "be", name: "Belarusian - Беларуская" },
  { code: "bn", name: "Bengali - বাংলা" },
  { code: "bs", name: "Bosnian - Bosanski" },
  { code: "bg", name: "Bulgarian - Български" },
  { code: "ca", name: "Catalan - Català" },
  { code: "ceb", name: "Cebuano" },
  { code: "ny", name: "Chichewa" },
  { code: "zh", name: "Chinese - 中文" },
  { code: "zh-TW", name: "Chinese (Traditional) - 繁體中文" },
  { code: "co", name: "Corsican - Corsu" },
  { code: "hr", name: "Croatian - Hrvatski" },
  { code: "cs", name: "Czech - Čeština" },
  { code: "da", name: "Danish - Dansk" },
  { code: "nl", name: "Dutch - Nederlands" },
  { code: "en", name: "English" },
  { code: "eo", name: "Esperanto" },
  { code: "et", name: "Estonian - Eesti" },
  { code: "tl", name: "Filipino - Tagalog" },
  { code: "fi", name: "Finnish - Suomi" },
  { code: "fr", name: "French - Français" },
  { code: "fy", name: "Frisian - Frysk" },
  { code: "gl", name: "Galician - Galego" },
  { code: "ka", name: "Georgian - ქართული" },
  { code: "de", name: "German - Deutsch" },
  { code: "el", name: "Greek - Ελληνικά" },
  { code: "gu", name: "Gujarati - ગુજરાતી" },
  { code: "ht", name: "Haitian Creole" },
  { code: "ha", name: "Hausa" },
  { code: "haw", name: "Hawaiian - ʻŌlelo Hawaiʻi" },
  { code: "iw", name: "Hebrew - עברית" },
  { code: "hi", name: "Hindi - हिन्दी" },
  { code: "hmn", name: "Hmong" },
  { code: "hu", name: "Hungarian - Magyar" },
  { code: "is", name: "Icelandic - Íslenska" },
  { code: "ig", name: "Igbo" },
  { code: "id", name: "Indonesian - Bahasa Indonesia" },
  { code: "ga", name: "Irish - Gaeilge" },
  { code: "it", name: "Italian - Italiano" },
  { code: "ja", name: "Japanese - 日本語" },
  { code: "jw", name: "Javanese - Basa Jawa" },
  { code: "kn", name: "Kannada - ಕನ್ನಡ" },
  { code: "kk", name: "Kazakh - Қазақ" },
  { code: "km", name: "Khmer - ភាសាខ្មែរ" },
  { code: "ko", name: "Korean - 한국어" },
  { code: "ku", name: "Kurdish - Kurdî" },
  { code: "ky", name: "Kyrgyz - Кыргызча" },
  { code: "lo", name: "Lao - ລາວ" },
  { code: "la", name: "Latin" },
  { code: "lv", name: "Latvian - Latviešu" },
  { code: "lt", name: "Lithuanian - Lietuvių" },
  { code: "lb", name: "Luxembourgish - Lëtzebuergesch" },
  { code: "mk", name: "Macedonian - Македонски" },
  { code: "mg", name: "Malagasy" },
  { code: "ms", name: "Malay - Bahasa Melayu" },
  { code: "ml", name: "Malayalam - മലയാളം" },
  { code: "mt", name: "Maltese - Malti" },
  { code: "mi", name: "Maori" },
  { code: "mr", name: "Marathi - मराठी" },
  { code: "mn", name: "Mongolian - Монгол" },
  { code: "my", name: "Myanmar (Burmese) - မြန်မာ" },
  { code: "ne", name: "Nepali - नेपाली" },
  { code: "no", name: "Norwegian - Norsk" },
  { code: "ps", name: "Pashto - پښتو" },
  { code: "fa", name: "Persian - فارسی" },
  { code: "pl", name: "Polish - Polski" },
  { code: "pt", name: "Portuguese - Português" },
  { code: "pa", name: "Punjabi - ਪੰਜਾਬੀ" },
  { code: "ro", name: "Romanian - Română" },
  { code: "ru", name: "Russian - Русский" },
  { code: "sm", name: "Samoan" },
  { code: "gd", name: "Scots Gaelic - Gàidhlig" },
  { code: "sr", name: "Serbian - Српски" },
  { code: "st", name: "Sesotho" },
  { code: "sn", name: "Shona" },
  { code: "sd", name: "Sindhi - سنڌي" },
  { code: "si", name: "Sinhala - සිංහල" },
  { code: "sk", name: "Slovak - Slovenčina" },
  { code: "sl", name: "Slovenian - Slovenščina" },
  { code: "so", name: "Somali - Soomaali" },
  { code: "es", name: "Spanish - Español" },
  { code: "su", name: "Sundanese - Basa Sunda" },
  { code: "sw", name: "Swahili - Kiswahili" },
  { code: "sv", name: "Swedish - Svenska" },
  { code: "tg", name: "Tajik - Тоҷикӣ" },
  { code: "ta", name: "Tamil - தமிழ்" },
  { code: "te", name: "Telugu - తెలుగు" },
  { code: "th", name: "Thai - ไทย" },
  { code: "tr", name: "Turkish - Türkçe" },
  { code: "uk", name: "Ukrainian - Українська" },
  { code: "ur", name: "Urdu - اردو" },
  { code: "uz", name: "Uzbek - Oʻzbek" },
  { code: "vi", name: "Vietnamese - Tiếng Việt" },
  { code: "cy", name: "Welsh - Cymraeg" },
  { code: "xh", name: "Xhosa - isiXhosa" },
  { code: "yi", name: "Yiddish - ייִדיש" },
  { code: "yo", name: "Yoruba - Yorùbá" },
  { code: "zu", name: "Zulu - isiZulu" },
];
