// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's Prayer & Fire profile (username, email, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client(ctx).from("profiles").select("id, username, email, avatar_url, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-events.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_events_default = defineTool2({
  name: "list_events",
  title: "List upcoming events",
  description: "List upcoming Prayer & Fire events (active, ordered by date).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max events to return. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client2(ctx).from("events").select("id, title, description, event_date, end_date, location, is_online, registration_url").eq("is_active", true).gte("event_date", (/* @__PURE__ */ new Date()).toISOString()).order("event_date", { ascending: true }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-notifications.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_notifications_default = defineTool3({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List notifications addressed to the signed-in user (personal and broadcast).",
  inputSchema: {
    unread_only: z2.boolean().optional().describe("Return only unread notifications. Default false."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max notifications to return. Default 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = client3(ctx).from("notifications").select("id, title, message, type, link, is_read, created_at, user_id").order("created_at", { ascending: false }).limit(limit ?? 30);
    if (unread_only) q = q.eq("is_read", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { notifications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-purchases.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_purchases_default = defineTool4({
  name: "list_my_purchases",
  title: "List my purchases",
  description: "List the signed-in user's purchases, including product name and price paid.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client4(ctx).from("purchases").select("id, purchase_date, price_paid, products(name, category)").eq("user_id", ctx.getUserId()).order("purchase_date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { purchases: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/rsvp-event.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var rsvp_event_default = defineTool5({
  name: "rsvp_event",
  title: "RSVP to an event",
  description: "Create an RSVP for the signed-in user for a given event id.",
  inputSchema: {
    event_id: z3.string().uuid().describe("Event UUID from list_events.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ event_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client5(ctx).from("event_rsvps").upsert({ event_id, user_id: ctx.getUserId() }, { onConflict: "event_id,user_id" }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `RSVP saved for event ${event_id}.` }],
      structuredContent: { rsvp: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yufzlqcuvmirniruwyio";
var mcp_default = defineMcp({
  name: "prayer-and-fire-mcp",
  title: "Prayer & Fire",
  version: "0.1.0",
  instructions: "Tools for the Prayer & Fire app. Read the signed-in user's profile, notifications, and purchases; list upcoming events; and RSVP to an event. All tools act as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_events_default, list_my_notifications_default, list_my_purchases_default, rsvp_event_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
